//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kiwi.Tpv.App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kiwi.Tpv.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Botella.
        /// </summary>
        internal static string Botella {
            get {
                return ResourceManager.GetString("Botella", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conectada.
        /// </summary>
        internal static string CajaConectada {
            get {
                return ResourceManager.GetString("CajaConectada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desconectada.
        /// </summary>
        internal static string CajaDesconectada {
            get {
                return ResourceManager.GetString("CajaDesconectada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,00€.
        /// </summary>
        internal static string CeroEuros {
            get {
                return ResourceManager.GetString("CeroEuros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración guardada correctamente.
        /// </summary>
        internal static string ConfiguracionGuardadOk {
            get {
                return ResourceManager.GetString("ConfiguracionGuardadOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empleados [Editar].
        /// </summary>
        internal static string EmpleadosEditar {
            get {
                return ResourceManager.GetString("EmpleadosEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empleados [Nuevo].
        /// </summary>
        internal static string EmpleadosNuevo {
            get {
                return ResourceManager.GetString("EmpleadosNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de conexión.
        /// </summary>
        internal static string ErrorConexion {
            get {
                return ResourceManager.GetString("ErrorConexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de conexión con la base de datos.
        /// </summary>
        internal static string ErrorConexionBD {
            get {
                return ResourceManager.GetString("ErrorConexionBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de estación.
        /// </summary>
        internal static string ErrorEstacion {
            get {
                return ResourceManager.GetString("ErrorEstacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al guardar la configuración.
        /// </summary>
        internal static string ErrorGuardarConfiguracion {
            get {
                return ResourceManager.GetString("ErrorGuardarConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La estación actual no esta configurada o no existe.
        /// </summary>
        internal static string EstacionNoExiste {
            get {
                return ResourceManager.GetString("EstacionNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  €.
        /// </summary>
        internal static string Euro {
            get {
                return ResourceManager.GetString("Euro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel files (*.xlsx)|*.xlsx|All files (*.*)|*.*.
        /// </summary>
        internal static string ExcelExtensionFilter {
            get {
                return ResourceManager.GetString("ExcelExtensionFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportación a Excel.
        /// </summary>
        internal static string ExportacionExcel {
            get {
                return ResourceManager.GetString("ExportacionExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportación finalizada correctamente.
        /// </summary>
        internal static string ExportacionExcelCorrecta {
            get {
                return ResourceManager.GetString("ExportacionExcelCorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar configuración.
        /// </summary>
        internal static string GuardarConfiguracion {
            get {
                return ResourceManager.GetString("GuardarConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icoClose {
            get {
                object obj = ResourceManager.GetObject("icoClose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icoMaximize {
            get {
                object obj = ResourceManager.GetObject("icoMaximize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icoMinimize {
            get {
                object obj = ResourceManager.GetObject("icoMinimize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files (*.bmp, *.jpg, *.png, *.gif)|*.bmp;*.jpg;*.png;*.gif.
        /// </summary>
        internal static string ImageFilters {
            get {
                return ResourceManager.GetString("ImageFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap jager {
            get {
                object obj = ResourceManager.GetObject("jager", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Jomita {
            get {
                return ResourceManager.GetStream("Jomita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación no realizada..
        /// </summary>
        internal static string OperacionNoOk {
            get {
                return ResourceManager.GetString("OperacionNoOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación realizada correctamente..
        /// </summary>
        internal static string OperacionOk {
            get {
                return ResourceManager.GetString("OperacionOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream PimPam {
            get {
                return ResourceManager.GetStream("PimPam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos [Editar].
        /// </summary>
        internal static string ProductosEditar {
            get {
                return ResourceManager.GetString("ProductosEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos [Nuevo].
        /// </summary>
        internal static string ProductosNuevo {
            get {
                return ResourceManager.GetString("ProductosNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rdlc files (*.rdlc)|*rdlc.
        /// </summary>
        internal static string ReportExtensionFilter {
            get {
                return ResourceManager.GetString("ReportExtensionFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream TrucuTrucu {
            get {
                return ResourceManager.GetStream("TrucuTrucu", resourceCulture);
            }
        }
    }
}
