//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kiwi.Tpv.App.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kiwi.Tpv.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Botella.
        /// </summary>
        internal static string Botella {
            get {
                return ResourceManager.GetString("Botella", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conectada.
        /// </summary>
        internal static string CajaConectada {
            get {
                return ResourceManager.GetString("CajaConectada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desconectada.
        /// </summary>
        internal static string CajaDesconectada {
            get {
                return ResourceManager.GetString("CajaDesconectada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0,00€.
        /// </summary>
        internal static string CeroEuros {
            get {
                return ResourceManager.GetString("CeroEuros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración guardada correctamente.
        /// </summary>
        internal static string ConfiguracionGuardadOk {
            get {
                return ResourceManager.GetString("ConfiguracionGuardadOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empleados [Editar].
        /// </summary>
        internal static string EmpleadosEditar {
            get {
                return ResourceManager.GetString("EmpleadosEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empleados [Nuevo].
        /// </summary>
        internal static string EmpleadosNuevo {
            get {
                return ResourceManager.GetString("EmpleadosNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de conexión.
        /// </summary>
        internal static string ErrorConexion {
            get {
                return ResourceManager.GetString("ErrorConexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de conexión con la base de datos.
        /// </summary>
        internal static string ErrorConexionBD {
            get {
                return ResourceManager.GetString("ErrorConexionBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de estación.
        /// </summary>
        internal static string ErrorEstacion {
            get {
                return ResourceManager.GetString("ErrorEstacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al guardar la configuración.
        /// </summary>
        internal static string ErrorGuardarConfiguracion {
            get {
                return ResourceManager.GetString("ErrorGuardarConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La estación actual no esta configurada o no existe.
        /// </summary>
        internal static string EstacionNoExiste {
            get {
                return ResourceManager.GetString("EstacionNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  €.
        /// </summary>
        internal static string Euro {
            get {
                return ResourceManager.GetString("Euro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excel files (*.xlsx)|*.xlsx|All files (*.*)|*.*.
        /// </summary>
        internal static string ExcelExtensionFilter {
            get {
                return ResourceManager.GetString("ExcelExtensionFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportación a Excel.
        /// </summary>
        internal static string ExportacionExcel {
            get {
                return ResourceManager.GetString("ExportacionExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportación finalizada correctamente.
        /// </summary>
        internal static string ExportacionExcelCorrecta {
            get {
                return ResourceManager.GetString("ExportacionExcelCorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar configuración.
        /// </summary>
        internal static string GuardarConfiguracion {
            get {
                return ResourceManager.GetString("GuardarConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icoClose {
            get {
                object obj = ResourceManager.GetObject("icoClose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icoMaximize {
            get {
                object obj = ResourceManager.GetObject("icoMaximize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icoMinimize {
            get {
                object obj = ResourceManager.GetObject("icoMinimize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Image Files (*.bmp, *.jpg, *.png, *.gif)|*.bmp;*.jpg;*.png;*.gif.
        /// </summary>
        internal static string ImageFilters {
            get {
                return ResourceManager.GetString("ImageFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operación no realizada..
        /// </summary>
        internal static string OperacionNoOk {
            get {
                return ResourceManager.GetString("OperacionNoOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operación realizada correctamente..
        /// </summary>
        internal static string OperacionOk {
            get {
                return ResourceManager.GetString("OperacionOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos [Editar].
        /// </summary>
        internal static string ProductosEditar {
            get {
                return ResourceManager.GetString("ProductosEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos [Nuevo].
        /// </summary>
        internal static string ProductosNuevo {
            get {
                return ResourceManager.GetString("ProductosNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rdlc files (*.rdlc)|*rdlc.
        /// </summary>
        internal static string ReportExtensionFilter {
            get {
                return ResourceManager.GetString("ReportExtensionFilter", resourceCulture);
            }
        }
    }
}
